In [2]:
from Thymio import Thymio
import numpy as np
import matplotlib.pyplot as plt
import math as m
import time

In [41]:
A = np.array([[1, 0, 0, 0.1*m.cos(m.pi/4)/2, 0.1*m.cos(m.pi/4)/2],[0, 1, 0, 0.1*m.cos(m.pi/4)/2, 0.1*m.sin(m.pi/4)/2],\
             [0, 0, 1, 1/(2*4.7), 1/(2*4.7)],[0, 0, 0, 1, 0],[0, 0, 0, 0, 1]]) 

Q = np.zeros((5,5))
print(Q)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [35]:
theta = m.pi
vTOm = 1
sig = 6.15
Ts = 0.1

Q[0][0] = sig*(m.cos(theta)**2)*(Ts**3)/(3*2*(vTOm**2))
Q[0][1] = sig*(m.cos(theta)*m.sin(theta))*(Ts**3)/(3*2*(vTOm**2))
Q[0][2] = sig*(m.cos(theta)**2)*(Ts**3)/(3*4*(vTOm**2)) + sig*(m.cos(theta)*m.sin(theta))*(Ts**3)/(3*4*(vTOm**2))
Q[0][3] = sig*m.cos(theta)*(Ts**2)/(2*2*(vTOm**2))
Q[0][4] = sig*m.cos(theta)*(Ts**2)/(2*2*(vTOm**2))

TypeError: 'numpy.float64' object does not support item assignment