In [2]:
from Thymio import Thymio
import numpy as np
import matplotlib.pyplot as plt
import math as m
import time

In [7]:
A = np.array([[1, 0, 0, 0.1*m.cos(m.pi/4)/2, 0.1*m.cos(m.pi/4)/2],[0, 1, 0, 0.1*m.cos(m.pi/4)/2, 0.1*m.sin(m.pi/4)/2],\
             [0, 0, 1, 1/(2*4.7), 1/(2*4.7)],[0, 0, 0, 1, 0],[0, 0, 0, 0, 1]]) 

Q = np.array([[1.,0.,0.,0.,0.],[0.,1.,0.,0.,0.],[0.,0.,1.,0.,0.],[0.,0.,0.,6.15,0.],[0.,0.,0.,0.,6.15]]) 

[[1.         0.         0.         0.03535534 0.03535534]
 [0.         1.         0.         0.03535534 0.03535534]
 [0.         0.         1.         0.10638298 0.10638298]
 [0.         0.         0.         1.         0.        ]
 [0.         0.         0.         0.         1.        ]]


array([[0.        , 1.        , 0.        , 0.03535534, 0.03535534],
       [0.        , 0.        , 1.        , 0.10638298, 0.10638298]])